# -*- coding: utf-8 -*-
"""CS315_Project_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w66HNE9A8twp65YIdoNi9_R1B5GoQcg3

# BLACKJACK GAME
"""

#----------------------------------------
#  CSC 315 / 615 Spring 2023
#  Project 1 Blackjack
#
#  Nicey Raiyani
#----------------------------------------


#------
# import used for shuffling deck
#  do not change
#------
import itertools, random


#------------
# PrintCard
#   this function prints a card (number,suit) 
#   in the form of "Ace of Spade" or "3 of Diamond"
#------------
def PrintCard(card):

  suit = card[0]
  if card[0] == 11:
    suit = 'Jack'
  if card[0] == 12:
    suit = 'Queen'
  if card[0] == 13:
    suit = 'King'
  if card[0] == 1:
    suit = 'Ace'
  print("  ", suit, "of", card[1],)


#------------
# HandValue
#   input:   a list of cards called a hand
#   output:  a number describing the value of the hand
#------------
def HandValue(hand, value):

  if card[0] == 1 and (value+11 <= 21):
    return 11
  elif card[0] >= 11:
    return 10
  else:
    return card[0]
    


#----------------------------------------
# Main execution starts here
#----------------------------------------

#------------
# Construct a deck and shuffle it.
#  shuffle code from Python example
#  do not modify
#------------
deck = list(itertools.product(range(1,14),['Spade','Heart','Diamond','Club']))
random.shuffle(deck)


#---------
# Main game loop to play Blackjack
#  Implement the main pseudocode here
#
# ToDo:  You must heavily modify the following
#
#---------
value = 0
endgame = False
counter = 1
#GAME STARTS

while True:
  if endgame == True:
    break
  
  if counter > len(deck):
    print('You have run out of cards!')
    break
  ace11 = False
  print('----------------------------')
  value = 0
  print('Dealer has 18:')
  print('You have:')
    # Card 1
  card = deck[counter]
  counter+=1
  PrintCard(card)
  value+= HandValue(card, value)
  if HandValue(card,value) == 1:
    ace11 = True
    # Card 2
  card = deck[counter]
  counter+=1
  PrintCard(card)
  value+= HandValue(card, value)
  if HandValue(card,value) == 1:
    ace11 = True
    # print value
  print('value', value)
  


  while(True):

          #If more than 21 then loses game only if Stay is not chosen

    if value > 21:
      print('Busted, you lose!')
      while(True):
        answer = input('Play again? 1: Yes 2: No ')
        if answer == '1' or answer == '2':
          break
      if answer == '1':
        break;
      if answer == '2':
        print('GoodBye')
        endgame = True
        break

        #If more than 18 then wins game
    if value == 21:
      print('BlackJack, you win!')
      while(True):
        answer = input('Play again? 1: Yes 2: No ')
        if answer == '1' or answer == '2':
          break
      if answer == '1':
        break
      if answer == '2':
        print('GoodBye')
        endgame = True
        break
    
    while True:
        answer = input('What to do? 1: Hit 2: Stay ')
        if answer == '1' or answer == '2':
          break
    
    if answer == '1':
      #Draw a card
      card = deck[counter]
      counter+=1
      value+= HandValue(card, value)
      if HandValue(card,value) == 1:
        #boolean to keep count of ace
        ace11 = True
          # print value
      PrintCard(card)
      #For the extra credit: If it has had an Ace
      #where the value was considered 11, change
      #it to 1 to increase change of winning
      if ace11 == True and value > 21:
        value = value - 10
        ace11 = False
      print('value', value)
      continue

    if answer == '2':
      if value > 18:
        print('You beat 18, you win!')
        while(True):
          answer = input('Play again? 1: Yes 2: No ')
          if answer == '1' or answer == '2':
            break
        if answer == '1':
          break
        if answer == '2':
          endgame = True
          print('GoodBye')
          break
      
      elif value == 18:
        print('You tried 18, push!')
        while(True):
          answer = input('Play again? 1: Yes 2: No ')
          if answer == '1' or answer == '2':
            break
        if answer == '1':
          break
        if answer == '2':
          endgame = True
          print('GoodBye')
          break

      else:
        print('You came short, you lose!')
        while(True):
          answer = input('Play again? 1: Yes 2: No ')
          if answer == '1' or answer == '2':
            break
        if answer == '1':
          break
        if answer == '2':
          endgame = True
          print('GoodBye')
          break